# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e83d21b14ffd12807db93b12a71e9567413ba60303a087dcce5fbccbbd17e8e8b0101a2f1660bdcb656401a26ec72c84a9a4f42d8596ed30e729eb96ee64cc5b

test:
  secret_key_base: 5982447d086d7b89fe0264cce1eb6a3aaea3580bd6bc9c1d9dd0e729b3661f8eb7059250445771dda5108a037326f8a2e89c0408828324fb3543d88289bb8c4c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
